[package]
name = "bevy_web_extras"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.1" }
web-sys = { version = "0.3.56", features = ['Window'] }
wasm-bindgen = "0.2.79"
